# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-26 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.TextField()),
                ('color', models.TextField()),
            ],
        ),
    ]
